CREATE TABLE delivery (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	fee DECIMAL(5,2) NOT NULL
);

CREATE TABLE purchases (
	id INT PRIMARY KEY NOT NULL,
	title VARCHAR(255) NOT NULL,
	price DECIMAL(5,2),
	delivery INT
);